#ifndef RESOURCES_INCLUDED
#define RESOURCES_INCLUDED
#pragma once

#define RESOURCE_ID_WING1_DIFF		0x100
#define RESOURCE_ID_TRANSFER_DIFF	0x101
#define RESOURCE_ID_SM1_DIFF		0x102
#define RESOURCE_ID_SM2_DIFF        0x103
#define RESOURCE_ID_WING2_DIFF		0x104

#endif
