import "unknwn.idl";
import "wtypes.idl";

cpp_quote("#ifdef WCDX_EXPORTS")
cpp_quote("#define WCDXAPI __declspec(dllexport)")
cpp_quote("#else")
cpp_quote("#define WCDXAPI __declspec(dllimport)")
cpp_quote("#endif")

interface IWcdx;

typedef struct
{
	BYTE blue;
	BYTE green;
	BYTE red;
	BYTE alpha;
} WcdxColor;

cpp_quote("WCDXAPI IWcdx* WcdxCreate(LPCWSTR windowTitle, WNDPROC windowProc, BOOL fullScreen);")

[
	local,
	object,
	uuid(ab008bae-e9b4-411f-87d7-a7622a26c98b)
]
interface IWcdx : IUnknown
{
	HRESULT SetVisible(BOOL visible);
	HRESULT SetPalette([in] const WcdxColor entries[256]);
	HRESULT UpdatePalette(UINT index, [in, ref] const WcdxColor* entry);
	HRESULT UpdateFrame(INT x, INT y, UINT width, UINT height, UINT pitch, [in, size_is(height * pitch)] const byte* bits);
	HRESULT Present();

	HRESULT IsFullScreen();
	HRESULT ConvertPointToClient([in, out, ref] POINT* point);
	HRESULT ConvertPointFromClient([in, out, ref] POINT* point);
	HRESULT ConvertRectToClient([in, out, ref] RECT* rect);
	HRESULT ConvertRectFromClient([in, out, ref] RECT* rect);

	HRESULT SavedGameOpen([in, string] const wchar_t* subdir, [in, string] const wchar_t* filename, int oflag, int pmode, [out, ref] int* filedesc);
	HRESULT OpenFile([in, string] const char* filename, int oflag, int pmode, [out, ref] int* filedesc);
	HRESULT CloseFile(int filedesc);
	HRESULT WriteFile(int filedesc, long offset, unsigned size, [in, size_is(size)] const void* data);
	HRESULT ReadFile(int filedesc, long offset, unsigned size, [out, size_is(size)] void* data);
	HRESULT SeekFile(int filedesc, long offset, int method, [out, ref] long* position);
	HRESULT FileLength(int filedesc, [out, ref] long* length);
}
