import "unknwn.idl";
import "wtypes.idl";

cpp_quote("#ifdef WCDX_EXPORTS")
cpp_quote("#define WCDXAPI __declspec(dllexport)")
cpp_quote("#else")
cpp_quote("#define WCDXAPI __declspec(dllimport)")
cpp_quote("#endif")

interface IWcdx;

typedef struct
{
	BYTE blue;
	BYTE green;
	BYTE red;
	BYTE alpha;
} WcdxColor;

cpp_quote("WCDXAPI IWcdx* WcdxCreate(LPCWSTR windowTitle, WNDPROC windowProc, BOOL fullScreen);")

[
	local,
	object,
	uuid(ab008bae-e9b4-411f-87d7-a7622a26c98b)
]
interface IWcdx : IUnknown
{
	HRESULT SetVisible(BOOL visible);
	HRESULT SetPalette([in] const WcdxColor entries[256]);
	HRESULT UpdatePalette(UINT index, [in, ref] const WcdxColor* entry);
	HRESULT UpdateFrame(INT x, INT y, UINT width, UINT height, UINT pitch, [in, size_is(height * pitch)] const byte* bits);
	HRESULT Present();

	HRESULT IsFullScreen();
	HRESULT ConvertPointToScreen([in, out, ref] POINT* point);
	HRESULT ConvertPointFromScreen([in, out, ref] POINT* point);
	HRESULT ConvertRectToScreen([in, out, ref] RECT* rect);
	HRESULT ConvertRectFromScreen([in, out, ref] RECT* rect);
}
