import "unknwn.idl";
import "wtypes.idl";

cpp_quote("#ifdef WCDX_EXPORTS")
cpp_quote("#define WCDXAPI __declspec(dllexport)")
cpp_quote("#else")
cpp_quote("#define WCDXAPI __declspec(dllimport)")
cpp_quote("#endif")

interface IWcdx;

cpp_quote("WCDXAPI")
IWcdx* WcdxCreate(HWND window);

[
	local,
	object,
	uuid(ab008bae-e9b4-411f-87d7-a7622a26c98b)
]
interface IWcdx : IUnknown
{
	HRESULT SetPalette([in] const PALETTEENTRY entries[256]);
	HRESULT UpdatePalette(UINT index, [in, ref] const PALETTEENTRY* entry);
	HRESULT UpdateFrame(INT x, INT y, UINT width, UINT height, UINT pitch, [in, size_is(height * pitch)] const byte* bits);
	HRESULT Present();
}
